baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Williams Lab'
theme = 'williams'

[taxonomies]
  focus = 'foci'
  position = 'positions'
  person = 'people'
  fund = 'funding'
  category = 'categories'
  tag = 'tags'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Hannah'
    pageRef = '/people/williams-h'
    weight = 15  
  
  [[menus.main]]
    name = 'Research'
    pageRef = '/foci'
    weight = 20

  [[menus.main]]
    name = 'People'
    pageRef = '/people'
    weight = 30

  [[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 40